name: Build and Deploy Angular Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: ng build --aot --build-optimizer --base-href=/auto-build/

      - name: Deploy to live branch
        run: |
          git config user.name "loay98"
          git config user.email "loay@prosys.ai"
          git checkout -b live
          git rm -r --cached .
          git add dist/*   # Add only the contents of the dist directory
          git commit -m "Deploying latest build"
          git remote set-url origin https://$PAT_TOKEN@github.com/loay98/auto-build.git
          git push origin live
