name: Build and Deploy Angular

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add git name
        run: git config --global user.name "loay98"

      - name: Add git email
        run: git config --global user.email "losy@prosys.ai"

      - name: Fetch branch
        run: git fetch

      - name: Switch to live branch
        run: git checkout live --force

      # Files to keep
      - name: Delete all files
        run: find . -maxdepth 1 ! -name '.' ! -name 'ecosystem.config.js' ! -name 'pull-webhook.php' ! -name '.git' -exec rm -r {} \;

      - name: Stage the changes
        run: |
          git add .
          git commit -m "Delete all files"

      - name: Merge main to live branch
        run: git merge main --allow-unrelated-histories

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Set Base Href
          run: |
            # Get the repository name without the owner
            REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
            BASE_HREF="/auto-build/$REPO_NAME/"
            echo "BASE_HREF=$BASE_HREF" >> $GITHUB_ENV
          shell: bash

      - name: Build Angular application
        run: ng build --aot --build-optimizer --base-href=$BASE_HREF

      - name: Delete unwanted files and folders
        run: |
          find . -maxdepth 1 -type f ! -name '.gitignore' ! -name 'ecosystem.config.js' ! -name 'pull-webhook.php' -exec rm {} \;
          find . -maxdepth 1 -type d ! -name '.git' ! -name 'dist' -exec rm -r {} \;

      - name: Move folder out of output folder
        run: mv dist/$BASE_HREF/* .

      - name: Stage the changes
        run: |
          git add .
          git commit -m "Delete & Move files"

      - name: Push the changes to the remote repository
        run: git push

      - name: Fetch branch
        run: git fetch
