name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: ng build --aot --build-optimizer --base-href=/auto-build/

      - name: Set up Git
        run: |
          git config user.name "loay98"
          git config user.email "loay@prosys.ai"

      - name: Delete files in live branch
        run: |
          git checkout -B live
          git rm -rf .
          git commit -m "Remove all files from live branch"
          git push -f origin live

      - name: Copy dist folder to live branch
        run: |
          git checkout main
          git checkout live -- dist
          git add dist
          git commit -m "Update live branch with dist folder"
          git push origin live
