name: Build and Deploy Angular Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: ng build --prod

      - name: Deploy to live branch
        run: |
          git config user.name "loay98"
          git config user.email "loay@prosys.ai"
          git checkout -b live
          git add dist/   # Assuming your build output is in a 'dist' folder
          git commit -m "Deploying latest build"
          git push origin live

